version: '3'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=app-web-go
      - POSTGRES_PASSWORD=app-web-go
      - POSTGRES_DB=root      
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "thiagopmattos@hotmail.com"
      PGADMIN_DEFAULT_PASSWORD: "Sisco879206"
    ports:
      - "54321:80"
    depends_on:
      - postgres